version: '2'

services:
  3proxy:
    restart: always
    build: ./
    environment:
     - PROXY_LOGIN=admin
     - PROXY_PASSWORD=supersecurepasswordXD
    network_mode: "host"
#    ports:
#     - "192.168.255.50:8080:8080/tcp"
    volumes:
     - ./cfg:/etc/3proxy/cfg
